language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - phpenv config-add tests/travis_php_extensions.ini

install:
  - composer install --no-interaction

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1